<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tambah Iklan</name>
   <tag></tag>
   <elementGuidId>6c8614d5-ddc4-4973-bef0-c100ef9c8757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;promo-add&quot;)[count(. | //a[@id = 'promo-add' and @class = 'ml-10 action-button pull-left' and @data-popup-open = 'popup--promo' and (text() = 'Tambah Iklan' or . = 'Tambah Iklan')]) = count(//a[@id = 'promo-add' and @class = 'ml-10 action-button pull-left' and @data-popup-open = 'popup--promo' and (text() = 'Tambah Iklan' or . = 'Tambah Iklan')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promo-add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-10 action-button pull-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-open</name>
      <type>Main</type>
      <value>popup--promo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Iklan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo-add&quot;)</value>
   </webElementProperties>
</WebElementEntity>
